name: microscopy_proc
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - pip
  # Interactivity
  - ipykernel
  - fiji
  # Visualisation
  - python-graphviz
  # GPU acceleration
  - cupy
  - pip:
    - -e .
