name: microscopy_proc
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  # Interactivity
  - ipykernel
  - bioconda::fiji
  # Visualisation
  - python-graphviz
  # GPU acceleration (only CuPy from conda works)
  # - cuda-toolkit
  - cupy
  - pip:
      # - microscopy_proc
      # - -e "."
      - -e ".[gpu,elastix]"
