name: microscopy_proc
channels:
  # - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python
  - pip
  # Interactivity
  - ipykernel
  - fiji
  # Visualisation
  - python-graphviz
  # GPU acceleration
  # - cudatoolkit
  - cupy
  - pip:
    - -e .
